[workspace]
members  = ["crates/*"]
resolver = "2"


[workspace.dependencies]
napi-derive = "2.12.2"
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
serde ={ version = "1.0.121", features = ["derive"] }
oxc_allocator = {version = "0.22.1"}
oxc_parser = {version = "0.22.1"}
oxc_span = {version = "0.22.1"}
oxc_ast = {version = "0.22.1"}
oxc_syntax = {version = "0.22.1"}
oxc_semantic = {version = "0.22.1"}
oxc_sourcemap = {version = "0.22.1"}
oxc-browserslist = "1.0.3"
oxc_resolver = "1.11.0"
log = "0.4.22"
env_logger = "0.11.5"
anyhow = "1.0.80"
parking_lot = "0.12.3"

[profile.release]
lto = true
strip = "symbols"
opt-level = "z"
codegen-units = 1 

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]