[package]
edition = "2021"
name = "shined_source-code-diagnosis"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
wax = "0.6.0"
napi-derive = "2.12.2"
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
serde ={ version = "1.0.121", features = ["derive"] }
oxc_allocator = {version = "0.22.1"}
oxc_parser = {version = "0.22.1"}
oxc_span = {version = "0.22.1"}
oxc_ast = {version = "0.22.1"}
oxc_syntax = {version = "0.22.1"}
oxc_semantic = {version = "0.22.1"}
oxc_sourcemap = {version = "0.22.1"}
threadpool = "1.8.1"
rayon = "1.10.0" 
serde_json = "1.0.121"
serde_json5 = "0.1.0"
regex = "1.5.4"
lazy_static = "1.5.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
