[workspace]
members  = ["crates/*"]
resolver = "2"
 

[workspace.dependencies]
napi-derive = "2.12.2"
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
serde ={ version = "1.0.121", features = ["derive"] }
oxc_allocator = {version = "0.29.0"}
oxc_parser = {version = "0.29.0"}
oxc_span = {version = "0.29.0"}
oxc_ast = {version = "0.29.0"}
oxc_syntax = {version = "0.29.0"}
oxc_semantic = {version = "0.29.0"}
oxc_sourcemap = {version = "0.29.0"}
oxc-browserslist = "1.0.3"
oxc_resolver = "1.11.0"
log = "0.4.22"
env_logger = "0.11.5"
anyhow = "1.0.80"
parking_lot = "0.12.3"
serde_json = "1.0.128"
itertools = "0.12.0"
wax = "0.6.0"
camino = "1.1.9"
rayon = "1.10.0"
insta = "1.36.1"
pathdiff = "0.2"