name: CI
env:
  DEBUG: napi:*
  APP_NAME: source-code-diagnosis
  MACOSX_DEPLOYMENT_TARGET: '10.13'
permissions:
  contents: write
  id-token: write
on:
  release:
    types: [published, prereleased]
  push:
    branches: [test]
    
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Publish and update release
        run: |
          TAG=${{github.ref_name}}
          gh release edit $TAG --draft=false --prerelease=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
